using Microsoft.EntityFrameworkCore;

namespace MagicApp.Models
{
    public class CardContext : DbContext
    {
        public CardContext(DbContextOptions<CardContext> options) : base(options) { }

        public DbSet<Card> Cards { get; set; } = null!;
        public DbSet<Color> Colors { get; set; } = null!;
        public DbSet<CardColor> CardColors { get; set; } = null!;
        public DbSet<SuperType> SuperTypes { get; set; } = null!;
        public DbSet<CardSuperType> CardSuperTypes { get; set; } = null!;
        public DbSet<CardType> CardTypes { get; set; } = null!;
        public DbSet<CardCardType> CardCardTypes { get; set; } = null!;

        //public DbSet<MagicSet> MagicSets { get; set; } = null!;

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // configure many to many relationship with Card and Color Entities
            modelBuilder.Entity<Card>().HasMany(co => co.Colors).WithMany(c => c.Cards).UsingEntity<CardColor>();

            // configure many to many relationship with Card and Supertype Entities
            modelBuilder.Entity<Card>().HasMany(st => st.SuperTypes).WithMany(c => c.Cards).UsingEntity<CardSuperType>();

            // configure many to many relationship with Card and Cardtype Entities
            modelBuilder.Entity<Card>().HasMany(ct => ct.CardTypes).WithMany(c => c.Cards).UsingEntity<CardCardType>();

            //// Define the relationship between Card and MagicSet
            //modelBuilder.Entity<Card>()
            //    .HasOne(c => c.MagicSet) // Each card belongs to one MagicSet
            //    .WithMany(ca => ca.Cards) // Each MagicSet can have many cards
            //    .HasForeignKey(c => c.SetId); // Set the foreign key property

            modelBuilder.Entity<Card>().HasData(
                new Card
                {
                    CardId = 1,
                    CardName = "Lightning Bolt",
                    ManaCost = 1,
                    Rarity = "Rare",
                    Power = null,
                    Toughness = null,
                },
                new Card
                {
                    CardId = 2,
                    CardName = "Time Walk",
                    ManaCost = 2,
                    Rarity = "Rare",
                    Power = null,
                    Toughness = null,
                },
                new Card
                {
                    CardId = 3,
                    CardName = "Ancestral Recall",
                    ManaCost = 1,
                    Rarity = "Rare",
                    Power = null,
                    Toughness = null,
                },
                new Card
                {
                    CardId = 4,
                    CardName = "Golos, Tireless Pilgram",
                    ManaCost = 5,
                    Rarity = "Mythic",
                    Power = 3,
                    Toughness = 5,
                }
            );

            modelBuilder.Entity<Color>().HasData(
                new Color { ColorId = 1, ColorName = "red" },
                new Color { ColorId = 2, ColorName = "blue" },
                new Color { ColorId = 3, ColorName = "green" },
                new Color { ColorId = 4, ColorName = "white" },
                new Color { ColorId = 5, ColorName = "black" },
                new Color { ColorId = 6, ColorName = "colorless" }
                );

            modelBuilder.Entity<SuperType>().HasData(
                new SuperType { SuperTypeId = 1, Name = "Basic"},
                new SuperType { SuperTypeId = 2, Name = "Legendary" },
                new SuperType { SuperTypeId = 3, Name = "Snow" },
                new SuperType { SuperTypeId = 4, Name = "World" }
                );

            modelBuilder.Entity<CardType>().HasData(
                new CardType { TypeId = 1, Name = "Artifact" },
                new CardType { TypeId = 2, Name = "Enchantment" },
                new CardType { TypeId = 3, Name = "Creature" },
                new CardType { TypeId = 4, Name = "Land" },
                new CardType { TypeId = 5, Name = "Planeswalker" },
                new CardType { TypeId = 6, Name = "Battle" },
                new CardType { TypeId = 7, Name = "Instant" },
                new CardType { TypeId = 8, Name = "Sorcery" }
                );

            modelBuilder.Entity<Card>()
                .HasMany(co => co.Colors)
                .WithMany(c => c.Cards)
                .UsingEntity(
                    cc => cc.HasData(
                        new { CardId = 1, ColorId = 1 },
                        new { CardId = 2, ColorId = 2 },
                        new { CardId = 3, ColorId = 2 },
                        new { CardId = 4, ColorId = 1 },
                        new { CardId = 4, ColorId = 2 },
                        new { CardId = 4, ColorId = 3 },
                        new { CardId = 4, ColorId = 4 },
                        new { CardId = 4, ColorId = 5 }
                        ));

            //modelBuilder.Entity<Card>()
            //    .HasMany(st => st.SuperTypes)
            //    .WithMany(c => c.Cards)
            //    .UsingEntity(
            //        cst => cst.HasData(
            //            new { CardId = 9, SuperTypeId = 2 }                       
            //            ));

            //modelBuilder.Entity<MagicSet>().HasData(
            //    new MagicSet { SetId = 1, Name = "Alpha"},
            //    new MagicSet { SetId = 2, Name = "Beta"},
            //    new MagicSet { SetId = 3, Name = "Unlimited"},
            //    new MagicSet { SetId = 4, Name = "Arabian Nights" },
            //    new MagicSet { SetId = 5, Name = "Antiquities" },
            //    new MagicSet { SetId = 6, Name = "Revised" },
            //    new MagicSet { SetId = 7, Name = "Legends" },
            //    new MagicSet { SetId = 8, Name = "The Dark" },
            //    new MagicSet { SetId = 9, Name = "Fallen Empires" },
            //    new MagicSet { SetId = 10, Name = "Fourth Edition" },
            //    new MagicSet { SetId = 11, Name = "Ice Age" },
            //    new MagicSet { SetId = 12, Name = "Chronicles" },
            //    new MagicSet { SetId = 13, Name = "Renaissance" },
            //    new MagicSet { SetId = 14, Name = "Homelands" },
            //    new MagicSet { SetId = 15, Name = "Alliances" },
            //    new MagicSet { SetId = 16, Name = "Mirage" },
            //    new MagicSet { SetId = 17, Name = "Visions" },
            //    new MagicSet { SetId = 18, Name = "Fifth Edition" },
            //    new MagicSet { SetId = 19, Name = "Portal" },
            //    new MagicSet { SetId = 20, Name = "Weatherlight" },
            //    new MagicSet { SetId = 21, Name = "Tempest" },
            //    new MagicSet { SetId = 22, Name = "Stronghold" },
            //    new MagicSet { SetId = 23, Name = "Exodus" },
            //    new MagicSet { SetId = 24, Name = "Portal Second Age" },
            //    new MagicSet { SetId = 25, Name = "Unglued" },
            //    new MagicSet { SetId = 26, Name = "Urza's Saga" },
            //    new MagicSet { SetId = 27, Name = "Anthologies" },
            //    new MagicSet { SetId = 28, Name = "Urza's Legacy" },
            //    new MagicSet { SetId = 29, Name = "Sixth Edition" },
            //    new MagicSet { SetId = 30, Name = "Portal Three Kingdoms" },
            //    new MagicSet { SetId = 31, Name = "Urza's Destiny" },
            //    new MagicSet { SetId = 32, Name = "Starter 1999" },
            //    new MagicSet { SetId = 33, Name = "Mercadian Masters" },
            //    new MagicSet { SetId = 34, Name = "Battle Royale" },
            //    new MagicSet { SetId = 35, Name = "Nemesis" },
            //    new MagicSet { SetId = 36, Name = "Starter 2000" },
            //    new MagicSet { SetId = 37, Name = "Prophecy" },
            //    new MagicSet { SetId = 38, Name = "Invasion" },
            //    new MagicSet { SetId = 39, Name = "Beatdown" },
            //    new MagicSet { SetId = 40, Name = "Planeshift" },
            //    new MagicSet { SetId = 41, Name = "Seventh Edition" },
            //    new MagicSet { SetId = 42, Name = "Apocalypse" },
            //    new MagicSet { SetId = 43, Name = "Odyssey" },
            //    new MagicSet { SetId = 44, Name = "Deckmasters 2001" },
            //    new MagicSet { SetId = 45, Name = "Torment" },
            //    new MagicSet { SetId = 46, Name = "Judgement" },
            //    new MagicSet { SetId = 47, Name = "Onslaught" },
            //    new MagicSet { SetId = 48, Name = "Legions" },
            //    new MagicSet { SetId = 49, Name = "Scourge" },
            //    new MagicSet { SetId = 50, Name = "Eighth Edition" },
            //    new MagicSet { SetId = 51, Name = "Mirrodin" },
            //    new MagicSet { SetId = 52, Name = "Darksteel" },
            //    new MagicSet { SetId = 53, Name = "Fifth Dawn" },
            //    new MagicSet { SetId = 54, Name = "Champions of Kamigawa" },
            //    new MagicSet { SetId = 55, Name = "Unhinged" },
            //    new MagicSet { SetId = 56, Name = "Betrayers of Kamigawa" },
            //    new MagicSet { SetId = 57, Name = "Ninth Edition" },
            //    new MagicSet { SetId = 58, Name = "Salvat 2005" },
            //    new MagicSet { SetId = 59, Name = "Ravnica: City of Guilds" },
            //    new MagicSet { SetId = 60, Name = "Guildpact" },
            //    new MagicSet { SetId = 61, Name = "Dissension" },
            //    new MagicSet { SetId = 62, Name = "Coldsnap" },
            //    new MagicSet { SetId = 63, Name = "Time Spiral" },
            //    new MagicSet { SetId = 64, Name = "Time Spiral Timeshifted" },
            //    new MagicSet { SetId = 65, Name = "Planar Chaos" },
            //    new MagicSet { SetId = 66, Name = "Future Sight" },
            //    new MagicSet { SetId = 67, Name = "Tenth Edition" },
            //    new MagicSet { SetId = 68, Name = "Masters Edition" },
            //    new MagicSet { SetId = 69, Name = "Lorwyn" },
            //    new MagicSet { SetId = 70, Name = "Duel Decks: Elves vs. Goblins" },
            //    new MagicSet { SetId = 71, Name = "Morningtide" },
            //    new MagicSet { SetId = 72, Name = "Shadowmoor" },
            //    new MagicSet { SetId = 73, Name = "Eventide" },
            //    new MagicSet { SetId = 74, Name = "From the Vault: Dragons" },
            //    new MagicSet { SetId = 75, Name = "Masters Edition II" },
            //    new MagicSet { SetId = 77, Name = "Shards of Alara" },
            //    new MagicSet { SetId = 78, Name = "Duel Decks: Jace vs. Chandra" },
            //    new MagicSet { SetId = 79, Name = "Conflux" },
            //    new MagicSet { SetId = 80, Name = "Duel Decks; Divine vs Demonic" },
            //    new MagicSet { SetId = 81, Name = "Alara Reborn" },
            //    new MagicSet { SetId = 82, Name = "Magic 2010" },
            //    new MagicSet { SetId = 83, Name = "Commander Theme Decks" },
            //    new MagicSet { SetId = 84, Name = "From the Vault: Exiled" },
            //    new MagicSet { SetId = 85, Name = "Planechase" },
            //    new MagicSet { SetId = 86, Name = "Masters Edition III" },
            //    new MagicSet { SetId = 87, Name = "Zendikar" },
            //    new MagicSet { SetId = 88, Name = "Duel Decks: Garruk vs. Liliana" },
            //    new MagicSet { SetId = 89, Name = "Premium Deck Series: Slivers" },
            //    new MagicSet { SetId = 90, Name = "WorldWake" },
            //    new MagicSet { SetId = 91, Name = "Rise of the Eldrazi" },
            //    new MagicSet { SetId = 92, Name = "Deck Builder's Toolkit" },
            //    new MagicSet { SetId = 93, Name = "Duels of the Planeswalkers" },
            //    new MagicSet { SetId = 94, Name = "Unlimited" },
            //    new MagicSet { SetId = 95, Name = "Archenemy" },
            //    new MagicSet { SetId = 96, Name = "Magic 2011" },
            //    new MagicSet { SetId = 97, Name = "From the Vault: Relics" },
            //    new MagicSet { SetId = 98, Name = "Duel Decks: Elspeth vs Tezzeret" },
            //    new MagicSet { SetId = 99, Name = "Scars of Mirrodin" },
            //    new MagicSet { SetId = 100, Name = "Magic Online Deck Series" },
            //    new MagicSet { SetId = 101, Name = "Premium Deck Series: Fire and Lightning" },
            //    new MagicSet { SetId = 102, Name = "Momir Basic Event Deck" },
            //    new MagicSet { SetId = 103, Name = "Salvat 2011" },
            //    new MagicSet { SetId = 104, Name = "Masters Edition IV" },
            //    new MagicSet { SetId = 105, Name = "Mirrodin Besieged" },
            //    new MagicSet { SetId = 106, Name = "Deckbuilder's Toolkit 2011" },
            //    new MagicSet { SetId = 107, Name = "Duel Decks: Knighs vs. Dragons" },
            //    new MagicSet { SetId = 108, Name = "New Phyrexia" },
            //    new MagicSet { SetId = 109, Name = "Commander" },
            //    new MagicSet { SetId = 110, Name = "Magic 2012" },
            //    new MagicSet { SetId = 111, Name = "From the Vault: Legends" },
            //    new MagicSet { SetId = 112, Name = "Duel Decks: Ajani vs. Nicol Bolas" },
            //    new MagicSet { SetId = 113, Name = "Innistrad" },
            //    new MagicSet { SetId = 114, Name = "Premium Deck Series: Graveborn" },
            //    new MagicSet { SetId = 115, Name = "Dark Ascension" },
            //    new MagicSet { SetId = 116, Name = "Duel Decks: Venser vs. Koth" },
            //    new MagicSet { SetId = 117, Name = "Avacyn Restored" },
            //    new MagicSet { SetId = 118, Name = "Planechase 2012" },
            //    new MagicSet { SetId = 119, Name = "Magic 2013" },
            //    new MagicSet { SetId = 120, Name = "From the Vault: Realms" },
            //    new MagicSet { SetId = 121, Name = "Duel Decks: Izzet vs. Golgari" },
            //    new MagicSet { SetId = 122, Name = "Gatecrash" },
            //    new MagicSet { SetId = 123, Name = "Duel Decks: Sorin vs. Tibalt" },
            //    new MagicSet { SetId = 124, Name = "Dragon's Maze" },
            //    new MagicSet { SetId = 125, Name = "Modern Masters" },
            //    new MagicSet { SetId = 126, Name = "Magic 2014" },
            //    new MagicSet { SetId = 127, Name = "From the Vault: Twenty" },
            //    new MagicSet { SetId = 128, Name = "Duel Decks: Heroes vs. Monsters" },
            //    new MagicSet { SetId = 129, Name = "Theros" },
            //    new MagicSet { SetId = 130, Name = "Commander 2013" },
            //    new MagicSet { SetId = 140, Name = "Born of The Gods" },
            //    new MagicSet { SetId = 141, Name = "Duel Decks: Jace vs. Vraska" },
            //    new MagicSet { SetId = 142, Name = "Journey into Nyx" },
            //    new MagicSet { SetId = 143, Name = "Modern Event Deck" },
            //    new MagicSet { SetId = 144, Name = "Conspiracy" },
            //    new MagicSet { SetId = 145, Name = "Vintage Masters" },
            //    new MagicSet { SetId = 146, Name = "Magic 2015" },
            //    new MagicSet { SetId = 147, Name = "From the Vault: Annihilation" },
            //    new MagicSet { SetId = 148, Name = "Duel Decks: Speed vs. Cunning" },
            //    new MagicSet { SetId = 149, Name = "Khans of Tarkir" },
            //    new MagicSet { SetId = 150, Name = "Commander 2014" },
            //    new MagicSet { SetId = 151, Name = "Duel Decks Anthology" },
            //    new MagicSet { SetId = 131, Name = "Fate Reforged" },
            //    new MagicSet { SetId = 153, Name = "Duel Decks: Elspeth vs. Kiora" },
            //    new MagicSet { SetId = 154, Name = "Dragons of Tarkir" },
            //    new MagicSet { SetId = 155, Name = "Tempest Remastered" },
            //    new MagicSet { SetId = 156, Name = "Modern Masters 2015" },
            //    new MagicSet { SetId = 157, Name = "Magic Origins" },
            //    new MagicSet { SetId = 158, Name = "From the Vault: Angels" },
            //    new MagicSet { SetId = 159, Name = "Duel Decks: Zendikar vs. Eldrazi" },
            //    new MagicSet { SetId = 160, Name = "Battle for Zendikar" },
            //    new MagicSet { SetId = 161, Name = "Zendikar Expeditions" },
            //    new MagicSet { SetId = 162, Name = "Commander 2015" },
            //    new MagicSet { SetId = 163, Name = "Legendary Cube" },
            //    new MagicSet { SetId = 164, Name = "Oath of the Gatewatch" },
            //    new MagicSet { SetId = 165, Name = "Duel Decks: Blessed vs. Cursed" },
            //    new MagicSet { SetId = 166, Name = "Welcome Deck 2016" },
            //    new MagicSet { SetId = 167, Name = "Shadows over Innistrad" },
            //    new MagicSet { SetId = 168, Name = "Eternal Masters" },
            //    new MagicSet { SetId = 169, Name = "Eldritch Moon" },
            //    new MagicSet { SetId = 170, Name = "From the Vault: Lore" },
            //    new MagicSet { SetId = 171, Name = "Conspiracy: Take the Crown" },
            //    new MagicSet { SetId = 172, Name = "Duel Decks: Nissa vs. Ob Nixilis" },
            //    new MagicSet { SetId = 173, Name = "Kaladesh" },
            //    new MagicSet { SetId = 174, Name = "Kaladesh Inventions" },
            //    new MagicSet { SetId = 175, Name = "Treasure Chests" },
            //    new MagicSet { SetId = 176, Name = "Commander 2016" },
            //    new MagicSet { SetId = 177, Name = "You Make the Cube" },
            //    new MagicSet { SetId = 178, Name = "Planechase Anthology" },
            //    new MagicSet { SetId = 179, Name = "Aether Revolt" },
            //    new MagicSet { SetId = 180, Name = "Modern Masters 2017" },
            //    new MagicSet { SetId = 181, Name = "Amonkhet" },
            //    new MagicSet { SetId = 182, Name = "Amonkhet Invocations" },
            //    new MagicSet { SetId = 183, Name = "Commander Anthology" },
            //    new MagicSet { SetId = 184, Name = "Archenemy: Nicol Bolas" },
            //    new MagicSet { SetId = 185, Name = "Hour of Devastation" },
            //    new MagicSet { SetId = 186, Name = "Commander 2017" },
            //    new MagicSet { SetId = 187, Name = "Ixalan" },
            //    new MagicSet { SetId = 188, Name = "Duel Decks: Merfolk vs. Goblins" },
            //    new MagicSet { SetId = 189, Name = "Iconic Masters" },
            //    new MagicSet { SetId = 190, Name = "Explorers of Ixalan" },
            //    new MagicSet { SetId = 191, Name = "From the Vault: Transform" },
            //    new MagicSet { SetId = 192, Name = "Unstable" },
            //    new MagicSet { SetId = 193, Name = "Rivals of Ixalan" },
            //    new MagicSet { SetId = 194, Name = "Masters 25" },
            //    new MagicSet { SetId = 195, Name = "Duel Decks: Elves vs. Inventors" },
            //    new MagicSet { SetId = 196, Name = "Challenger Decks" },
            //    new MagicSet { SetId = 197, Name = "Dominaria" },
            //    new MagicSet { SetId = 198, Name = "Commander Anthology Volume II" },
            //    new MagicSet { SetId = 199, Name = "Battlebond" },
            //    new MagicSet { SetId = 200, Name = "Signature Spellbook: Jace" },
            //    new MagicSet { SetId = 201, Name = "Global Series: Jiang Yanggu & Mu Yanling" },
            //    new MagicSet { SetId = 202, Name = "Core Set 2019" },
            //    new MagicSet { SetId = 203, Name = "Commander 2018" },
            //    new MagicSet { SetId = 204, Name = "Guild of Ravnica Mythic Edition" },
            //    new MagicSet { SetId = 205, Name = "Guild of Ravnica" },
            //    new MagicSet { SetId = 206, Name = "Spellslinger Starter Kit" },
            //    new MagicSet { SetId = 207, Name = "Guild of Ravnica Guild Kits" },
            //    new MagicSet { SetId = 208, Name = "Game Night" },
            //    new MagicSet { SetId = 209, Name = "Ultimate Masters" },
            //    new MagicSet { SetId = 210, Name = "Ravnica Allegiance Mythic Edition" },
            //    new MagicSet { SetId = 211, Name = "Ravnica Allegiance Guild Kits" },
            //    new MagicSet { SetId = 212, Name = "Challenger Decks 2019" },
            //    new MagicSet { SetId = 213, Name = "War of the Spark Mythic Edition" },
            //    new MagicSet { SetId = 214, Name = "War of the Spark" } ,
            //    new MagicSet { SetId = 215, Name = "Modern Horizons" },
            //    new MagicSet { SetId = 216, Name = "Signature Spellbook: Gideon" },
            //    new MagicSet { SetId = 217, Name = "Core Set 2020" },
            //    new MagicSet { SetId = 218, Name = "Commander 2019" },
            //    new MagicSet { SetId = 219, Name = "Throne of Eldraine" },
            //    new MagicSet { SetId = 220, Name = "Ponies the Galloping" },
            //    new MagicSet { SetId = 221, Name = "Mystery Booster" },
            //    new MagicSet { SetId = 222, Name = "Challenger Decks 2019 Japan" },
            //    new MagicSet { SetId = 223, Name = "Game Night 2019" },
            //    new MagicSet { SetId = 224, Name = "Secret Lair Drop Series(December 2019)" },
            //    new MagicSet { SetId = 225, Name = "Theros Beyond Death" },
            //    new MagicSet { SetId = 226, Name = "Secret Lair Drop Series: Year of the Rat" },
            //    new MagicSet { SetId = 227, Name = "Secret Lair Drop Series: Theros Stargazing" },
            //    new MagicSet { SetId = 228, Name = "Unsanctioned" },
            //    new MagicSet { SetId = 229, Name = "Secret Lair Drop Series: International Women's Day" },
            //    new MagicSet { SetId = 230, Name = "Secret Lair Drop Series: Thalia - Beyond the Helvault" },
            //    new MagicSet { SetId = 231, Name = "Mystery Booster Retail Edition" },
            //    new MagicSet { SetId = 232, Name = "Ikoria: Lair of Behemoths" },
            //    new MagicSet { SetId = 233, Name = "Commander 2020" },
            //    new MagicSet { SetId = 234, Name = "Secret Lair Drop Series: The Godzilla Lands " },
            //    new MagicSet { SetId = 235, Name = "Secret Lair Drop Series: Summer Superdrop" },
            //    new MagicSet { SetId = 236, Name = "Secret Lair: Ultimate Edition" },
            //    new MagicSet { SetId = 237, Name = "Signature Spellbook: Chandra" },
            //    new MagicSet { SetId = 238, Name = "Core Set 2021" },
            //    new MagicSet { SetId = 239, Name = "Jumpstart" },
            //    new MagicSet { SetId = 240, Name = "Double Masters" },
            //    new MagicSet { SetId = 241, Name = "Amonkhet Remastered" },
            //    new MagicSet { SetId = 242, Name = "Arena Base Set" },
            //    new MagicSet { SetId = 243, Name = "Secret Lair Drop Series: Prime Slime" },
            //    new MagicSet { SetId = 400, Name = "Secret Lair Drop Series: Every Dog Has Its Day" },
            //    new MagicSet { SetId = 401, Name = "Secret Lair Drop Series: Happy Yargle Day!" },
            //    new MagicSet { SetId = 244, Name = "Secret Lair Drop Series: April Fools" },
            //    new MagicSet { SetId = 245, Name = "Zendikar Rising" },
            //    new MagicSet { SetId = 246, Name = "Zendikar Rising Expeditions" },
            //    new MagicSet { SetId = 247, Name = "Zendikar Rising Commander Decks" },
            //    new MagicSet { SetId = 248, Name = "Secret Lair Drop Series: Showcase: Zendikar Revisited" },
            //    new MagicSet { SetId = 249, Name = "Secret Lair Drop Series: The Walking Dead" },
            //    new MagicSet { SetId = 250, Name = "Secret Lair Drop Series: Extra Life 2020" },
            //    new MagicSet { SetId = 251, Name = "Kaladesh Remastered" },
            //    new MagicSet { SetId = 252, Name = "Commander Legends" },
            //    new MagicSet { SetId = 253, Name = "Commander Legends Commander Decks" },
            //    new MagicSet { SetId = 254, Name = "Secret Lair Drop Series: Secretversary" },
            //    new MagicSet { SetId = 255, Name = "Commander Collection: Green" },
            //    new MagicSet { SetId = 256, Name = "Kaldheim" },
            //    new MagicSet { SetId = 257, Name = "Kaldheim Commander Decks" },
            //    new MagicSet { SetId = 258, Name = "Secret Lair Drop Series: Smitten" },
            //    new MagicSet { SetId = 259, Name = "Secret Lair Drop Series: Black is Magic" },
            //    new MagicSet { SetId = 260, Name = "Time Spiral Remastered" },
            //    new MagicSet { SetId = 261, Name = "Time Spiral Remastered Timeshifted"},
            //    new MagicSet { SetId = 262, Name = "CHallenger Decks 2021" },
            //    new MagicSet { SetId = 263, Name = "Strixhaven: School of Mages" },
            //    new MagicSet { SetId = 264, Name = "Mystical Archive" },
            //    new MagicSet { SetId = 265, Name = "Commander 2021" },
            //    new MagicSet { SetId = 266, Name = "Secret Lair Drop Series: Dr. Lair's Secretorium Superdrop" },
            //    new MagicSet { SetId = 267, Name = "Secret Lair: Ultimate Edition 2" },
            //    new MagicSet { SetId = 268, Name = "Modern Horizons II" },
            //    new MagicSet { SetId = 269, Name = "Secret Lair Drop Series: All-Natural, Totally Refreshing Superdrop" },
            //    new MagicSet { SetId = 270, Name = "Dungeons & Dragons: Adventures in the Forgotten Realms" },
            //    new MagicSet { SetId = 271, Name = "Dungeons & Dragons: Adventured in the Forgotten Realms Commander Decks" },
            //    new MagicSet { SetId = 272, Name = "2021 Arena Starter Kit" },
            //    new MagicSet { SetId = 273, Name = "Secret Lair Drop Series: Out of Time Superdrop" },
            //    new MagicSet { SetId = 274, Name = "Jumpstart: Historic Horizons" },
            //    new MagicSet { SetId = 275, Name = "Innistrad: Midnight Hunt" },
            //    new MagicSet { SetId = 276, Name = "Innistrad: Midnight Hunt Commander Decks" },
            //    new MagicSet { SetId = 277, Name = "Pioneer Challenger Decks" },
            //    new MagicSet { SetId = 278, Name = "Secret Lair Drop Series: October Superdrop" },
            //    new MagicSet { SetId = 279, Name = "Secret Lair Drop Series: Purrfection" },
            //    new MagicSet { SetId = 280, Name = "Secret Lair Drop Series: Extra Life 2021" },
            //    new MagicSet { SetId = 281, Name = "Innistrad: Crimson Vow" },
            //    new MagicSet { SetId = 282, Name = "Innistrad: Crimmson Vow Commander Decks" },
            //    new MagicSet { SetId = 283, Name = "Secret Lair Drop Series: MSCHF" },
            //    new MagicSet { SetId = 284, Name = "Secret Lair Drop Series: Secretversary 2021" },
            //    new MagicSet { SetId = 285, Name = "Secret Lair Drop Series: The Astrology Lands" },
            //    new MagicSet { SetId = 286, Name = "Commander Collection: Black" },
            //    new MagicSet { SetId = 287, Name = "Innistrad: Double Feature" },
            //    new MagicSet { SetId = 288, Name = "Secret Lair Drop Series: February Superdrop 2022" },
            //    new MagicSet { SetId = 289, Name = "Kamigawa: Neon Destiny" },
            //    new MagicSet { SetId = 290, Name = "Kamigawa: Neon Destiny Commander Decks" },
            //    new MagicSet { SetId = 291, Name = "Challenger Decks 2022" },
            //    new MagicSet { SetId = 292, Name = "Secret Lair Drop Series: April Superdrop" },
            //    new MagicSet { SetId = 293, Name = "Streets of New Capenna" },
            //    new MagicSet { SetId = 294, Name = "Streets of New Cappena Commander Decks" },
            //    new MagicSet { SetId = 295, Name = "Secret Lair Drop Series: Pride Across the Multiverse" },
            //    new MagicSet { SetId = 296, Name = "2022 Starter Kit" },
            //    new MagicSet { SetId = 297, Name = "Commander Legends: Battle for Baldur's Gate" },
            //    new MagicSet { SetId = 298, Name = "Commander Legends: Battle for Baldur's Gate Commaner Decks" },
            //    new MagicSet { SetId = 299, Name = "Secret Lair Drop Series: Here Be Dragons" },
            //    new MagicSet { SetId = 300, Name = "Secret Lair Drop Series: June Superdrop 2022" },
            //    new MagicSet { SetId = 301, Name = "Double Masters" },
            //    new MagicSet { SetId = 302, Name = "Secret Lair Drop Series: Fortnite" },
            //    new MagicSet { SetId = 303, Name = "Secret Lair Drop Series: :i'l Girl Saves the Day" },
            //    new MagicSet { SetId = 304, Name = "Secret Lair Drop Series: August Seuperdrop 2022" },
            //    new MagicSet { SetId = 305, Name = "Dominaria United" },
            //    new MagicSet { SetId = 306, Name = "Dominaris United Commander Decks" },
            //    new MagicSet { SetId = 307, Name = "Secret Lair Drop Series: Li'l'ler Walkers" },
            //    new MagicSet { SetId = 308, Name = "Unfinity" },
            //    new MagicSet { SetId = 309, Name = "Warghammer 40000 Commander Decks" },
            //    new MagicSet { SetId = 310, Name = "Game Night Free-For-All" },
            //    new MagicSet { SetId = 311, Name = "Secret Lair Drop Series: October Superdrop" },
            //    new MagicSet { SetId = 312, Name = "Secret Lair 30th Anniversary Countdown Kit" },
            //    new MagicSet { SetId = 313, Name = "Pioneer Challenger Decks 2022" },
            //    new MagicSet { SetId = 314, Name = "Secret Lair Drop Series: Extra Life 2022" },
            //    new MagicSet { SetId = 315, Name = "The Brother's War" },
            //    new MagicSet { SetId = 316, Name = "Retro Artifact Frames" },
            //    new MagicSet { SetId = 317, Name = "The Brother's War Commander Decks" },
            //    new MagicSet { SetId = 318, Name = "Transformers" },
            //    new MagicSet { SetId = 319, Name = "Jumpstart 2022" },
            //    new MagicSet { SetId = 320, Name = "Starter Commaner Decks" },
            //    new MagicSet { SetId = 321, Name = "Secret Lair Drop Series: December Superdrop 2022" },
            //    new MagicSet { SetId = 322, Name = "Dominaria Remastered" },
            //    new MagicSet { SetId = 323, Name = "Secret Lair Drop Series: Winter Superdrop 2023" },
            //    new MagicSet { SetId = 324, Name = "Phyrexia: All Will Be One" },
            //    new MagicSet { SetId = 325, Name = "Phyrexia: All Will Be One Commander Decks" },
            //    new MagicSet { SetId = 326, Name = "Secret Lair Drop Series: Legendary Flyers(Not That Kind)" },
            //    new MagicSet { SetId = 327, Name = "Secret Lair Drop Series: More Borderless Planeswalkers" },
            //    new MagicSet { SetId = 328, Name = "Shadows Over Innistrad Remastered" },
            //    new MagicSet { SetId = 329, Name = "Shadows of the Past" },
            //    new MagicSet { SetId = 330, Name = "Secret Lair Drop Series: Dungeons & Dragons: Honor Amongst Thieves" },
            //    new MagicSet { SetId = 331, Name = "March of the Machine" },
            //    new MagicSet { SetId = 332, Name = "Multiverse Legends" },
            //    new MagicSet { SetId = 333, Name = "March of the Machine Commander Decks" },
            //    new MagicSet { SetId = 334, Name = "March if the Machine: The Aftermath" },
            //    new MagicSet { SetId = 335, Name = "The Lord of the Rings: Tales of Middle-Earth" },
            //    new MagicSet { SetId = 336, Name = "The Lord of the Rings: Tales of Middle-Earth Commander Decks" },
            //    new MagicSet { SetId = 337, Name = "The Lord of the Rings: Tales of Middle-Earth Starter Kit" },
            //    new MagicSet { SetId = 338, Name = "Secret Lair Drop Series: Summer Superdrop 2023" },
            //    new MagicSet { SetId = 339, Name = "Commander Masters" },
            //    new MagicSet { SetId = 340, Name = "Commander Masters Commander Decks" },
            //    new MagicSet { SetId = 341, Name = "Secret Lair Commander Deck: Angels: They're Just Like Us but Cooler and with Wings" },
            //    new MagicSet { SetId = 342, Name = "Secret Lair Drop Series: Fall Superdrop 2023" },
            //    new MagicSet { SetId = 343, Name = "Wilds of Eldraine" },
            //    new MagicSet { SetId = 344, Name = "Enchanting Tales" },
            //    new MagicSet { SetId = 345, Name = "WIlds of Eldraine Commander Decks" },
            //    new MagicSet { SetId = 346, Name = "Starter Kit 2023" },
            //    new MagicSet { SetId = 347, Name = "Secret Lair Drop Series: Dan Frazier's Mox Box" },
            //    new MagicSet { SetId = 348, Name = "Ponies: The Galloping 2 - Extra Life 2023" },
            //    new MagicSet { SetId = 349, Name = "Secret Lair Drop Series: Li'l'est Planeswalkers" },
            //    new MagicSet { SetId = 350, Name = "Secret Lair Drop Series: Spookydrop 2023" },
            //    new MagicSet { SetId = 351, Name = "Doctor Who Commander Decks" },
            //    new MagicSet { SetId = 352, Name = "The Lord of the Rings: Holiday Release" },
            //    new MagicSet { SetId = 353, Name = "The Lost Caverns of Ixalan" },
            //    new MagicSet { SetId = 354, Name = "The Lost Caverns of Ixalan Commander Decks" },
            //    new MagicSet { SetId = 355, Name = "Jurassic World Collection" },
            //    new MagicSet { SetId = 356, Name = "Secret Lair Drop Series: Secretversary 2023" },
            //    new MagicSet { SetId = 357, Name = "Secret Lair: Calling All Hydra Heads" },
            //    new MagicSet { SetId = 358, Name = "Secret Lair Drop Series: Doctor Who: Regeneration" },
            //    new MagicSet { SetId = 359, Name = "Ravnica Remastered" },
            //    new MagicSet { SetId = 360, Name = "Secret Lair Commander Deck: Raining Cats and Dogs" },
            //    new MagicSet { SetId = 361, Name = "Secret Lair Drop Series: Winter Superdrop 2024" },
            //    new MagicSet { SetId = 362, Name = "Murders at Karlv Manor" },
            //    new MagicSet { SetId = 363, Name = "Murders at Karlov Manor Commander Decks" },
            //    new MagicSet { SetId = 364, Name = "Ravnica: Clue Edition" },
            //    new MagicSet { SetId = 365, Name = "Secret Lair Drop Series: Burning Revelations" },
            //    new MagicSet { SetId = 366, Name = "Secret Lair Drop Series: Sheldon's Spellbook" },
            //    new MagicSet { SetId = 367, Name = "Fallout" },
            //    new MagicSet { SetId = 368, Name = "The Big Score" },
            //    new MagicSet { SetId = 369, Name = "Outlaws of Thunder Junction" },
            //    new MagicSet { SetId = 370, Name = "Outlaws of Thunder Junction Commander Decks" },
            //    new MagicSet { SetId = 371, Name = "Modern Horizons III" },
            //    new MagicSet { SetId = 372, Name = "Modern Horizons III Commander Decks" },
            //    new MagicSet { SetId = 373, Name = "Assassin's Creed" },
            //    new MagicSet { SetId = 374, Name = "Bloomburrow" },
            //    new MagicSet { SetId = 375, Name = "Bloomburrow Commander Decks" },
            //    new MagicSet { SetId = 376, Name = "Duckmourn: House of Horror" },
            //    new MagicSet { SetId = 377, Name = "Pioneer Masters" },
            //    new MagicSet { SetId = 378, Name = "Innistrad Remastered" },
            //    new MagicSet { SetId = 379, Name = "Final Fantasy" },
            //    new MagicSet { SetId = 380, Name = "Marvel" }
            //    );




        } // end OnModelCreating
    } // end class
} // end namespace
